export const QueryKeys = {
  POKEDEX: `pokedex`,
  MOVES: `moves`,
  STATUS: `status`,
  STATS: `stats`,
  ABILITIES: `abilities`,
  TYPES: `types`,
  ITEMS: `items`,
  BERRIES: `berries`,
  MACHINES: `machines`,
  LOCATIONS: `locations`,
  FORMS: `forms`,
  ANALYSES: `analyses`,
  FORMATS: `formats`,
  SETS: `sets`,
  CARDS: `cards`,
  REGIONS: `regions`,
  SPECIES: `species`,
  EVOLUTIONS: `evolutions`,
  ABILITY: {
    INDEX: `ability`,
    POKEMON: `ability_pokemon`,
  },
  ITEM: `item`,
  MACHINE: `machine`,
  ENCOUNTER: {
    INDEX: `encounter`,
    CONDITION: `encounter_condition`,
    METHOD: `encounter_method`,
  },
  LOCATION: `location`,
  EVOLUTION: `evolution`,
  AREA: `area`,
  TYPE: {
    INDEX: `type`,
    POKEMON: `type_pokemon`,
    MOVES: `type_moves`,
  },
  MOVE: {
    INDEX: `move`,
    TARGET: `move_target`,
    POKEMON: `move_pokemon`,
  },
  POKEMON: {
    INDEX: `pokemon`,
    MOVES: `pokemon_moves`,
    MACHINES: {
      INDEX: `pokemon_machines`,
      TEMP: `pokemon_machines_temp`,
    },
  },
  USER: `user`,
} as const;
